script:
- python update.py -a ${OHLOH_KEY}
after_success:
- if [ "master" != $TRAVIS_BRANCH ]; then exit 0; fi;
- git config --global user.email "deploy@travis-ci.org"
- git config --global user.name "Travis deploy"
- git remote add github "https://${GH_TOKEN}@github.com/redecentralize/alternative-internet.git"
  > /dev/null
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}@github.com" > .git/credentials
- git checkout master
- git commit -a -m "Updating README.md with new project details [ci skip]"
- git push github master 
env:
  global:
    secure: "B0lrYAYfxgd0ku97K94xjjLOm+EhfSqnEVldwpMwex8TghWiD0u+Omns25H4xlSR9HDBM/84scgWA/GAbXAnvh7SFLlBu2Vfc/2V67UbrPuGvJRr9PpxEvOUCaSXguOWC1/C95Qww7YoFptPRxz8PXARf6eY5XYAX1cwX0DWT/s="
